/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\CC\\Desktop\\vuepress\\myvuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-78afc14c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78afc14c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-6d20d3b0",
    path: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/typora/%E5%AE%89%E8%A3%85pandoc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d20d3b0").then(next)
    },
  },
  {
    path: "/我的文章/typora/安装pandoc.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/typora/%E5%AE%89%E8%A3%85pandoc.html"
  },
  {
    path: "/我的文章/typora/安装pandoc.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/typora/%E5%AE%89%E8%A3%85pandoc.html"
  },
  {
    name: "v-5164cbda",
    path: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5164cbda").then(next)
    },
  },
  {
    path: "/我的文章/vuepress/侧边栏.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    path: "/我的文章/vuepress/侧边栏.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html"
  },
  {
    name: "v-5f9bdcaa",
    path: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f9bdcaa").then(next)
    },
  },
  {
    path: "/我的文章/vuepress/图片显示.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA.html"
  },
  {
    path: "/我的文章/vuepress/图片显示.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA.html"
  },
  {
    name: "v-295f4e8d",
    path: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-295f4e8d").then(next)
    },
  },
  {
    path: "/我的文章/vuepress/官方插件使用.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/我的文章/vuepress/官方插件使用.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-6c2252cf",
    path: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E6%8F%92%E4%BB%B6%E7%9C%8B%E6%9D%BF%E5%A8%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c2252cf").then(next)
    },
  },
  {
    path: "/我的文章/vuepress/插件看板娘.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E6%8F%92%E4%BB%B6%E7%9C%8B%E6%9D%BF%E5%A8%98.html"
  },
  {
    path: "/我的文章/vuepress/插件看板娘.html",
    redirect: "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E6%8F%92%E4%BB%B6%E7%9C%8B%E6%9D%BF%E5%A8%98.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-89d5379c",
    path: "/tag/typora/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-89d5379c").then(next)
    },
    meta: {"pid":"tags","id":"typora"}
  },
  {
    path: "/tag/typora/index.html",
    redirect: "/tag/typora/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-6e983184",
    path: "/categories/typora/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6e983184").then(next)
    },
    meta: {"pid":"categories","id":"typora"}
  },
  {
    path: "/categories/typora/index.html",
    redirect: "/categories/typora/"
  },
  {
    name: "v-9fa33418",
    path: "/categories/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-9fa33418").then(next)
    },
    meta: {"pid":"categories","id":"vuepress"}
  },
  {
    path: "/categories/vuepress/index.html",
    redirect: "/categories/vuepress/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]