/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "myblog",
  "description": "点赞、转发、收藏",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/bike.png"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress,自建博客"
      }
    ],
    [
      "meta",
      {
        "name": "description",
        "content": "专属于自学者的在线学习平台"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "robots",
        "content": "all"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "cc"
      }
    ],
    [
      "script",
      {
        "charset": "utf-8",
        "src": "/js/custom.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "神奇的个人博客",
        "bgImage": "/img/background.png",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": true,
        "features": [
          {
            "title": "Who am I？",
            "details": "A programmer? A human being? Or a matter combination?"
          },
          {
            "title": "Where am I？",
            "details": "In a city? On earth? Or in a small part of space?"
          },
          {
            "title": "What am I gona do？",
            "details": "Work? Struggle? Or go to a destination I don't know?"
          }
        ],
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-78afc14c",
      "path": "/",
      "lastUpdated": "2023/5/23 12:27:07",
      "lastUpdatedTimestamp": 1684816027000
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "title": "安装pandoc",
      "frontmatter": {
        "title": "安装pandoc",
        "date": "2023-05-25T00:00:00.000Z",
        "tags": [
          "typora"
        ],
        "categories": [
          "typora"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/typora/%E5%AE%89%E8%A3%85pandoc.html",
      "relativePath": "我的文章/typora/安装pandoc.md",
      "key": "v-6d20d3b0",
      "path": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/typora/%E5%AE%89%E8%A3%85pandoc.html",
      "headers": [
        {
          "level": 2,
          "title": "安装pandoc扩展程序",
          "slug": "安装pandoc扩展程序"
        },
        {
          "level": 3,
          "title": "检测安装是否成功",
          "slug": "检测安装是否成功"
        }
      ]
    },
    {
      "title": "侧边栏",
      "frontmatter": {
        "title": "侧边栏",
        "date": "2023-05-25T00:00:00.000Z",
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
      "relativePath": "我的文章/vuepress/侧边栏.md",
      "key": "v-5164cbda",
      "path": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "最后更新时间",
          "slug": "最后更新时间"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>This is a tip 更新时间</p>\n</div>"
    },
    {
      "title": "Vuepress 图片资源中文路径问题",
      "frontmatter": {
        "title": "Vuepress 图片资源中文路径问题",
        "date": "2023-05-27T00:00:00.000Z",
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA.html",
      "relativePath": "我的文章/vuepress/图片显示.md",
      "key": "v-5f9bdcaa",
      "path": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%9B%BE%E7%89%87%E6%98%BE%E7%A4%BA.html",
      "headers": [
        {
          "level": 2,
          "title": "不会出现图片无法加载的情况",
          "slug": "不会出现图片无法加载的情况"
        },
        {
          "level": 2,
          "title": "问题描述",
          "slug": "问题描述"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        }
      ],
      "excerpt": "<p><img src=\"./图片显示.assets/image-20230527172336150.png\" alt=\"image-20230527172336150\" /></p>\n"
    },
    {
      "title": "官方插件使用",
      "frontmatter": {
        "title": "官方插件使用",
        "date": "2023-05-25T00:00:00.000Z",
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html",
      "relativePath": "我的文章/vuepress/官方插件使用.md",
      "key": "v-295f4e8d",
      "path": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E5%AE%98%E6%96%B9%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "使用插件",
          "slug": "使用插件"
        },
        {
          "level": 2,
          "title": "禁用插件",
          "slug": "禁用插件"
        }
      ]
    },
    {
      "title": "看伴娘",
      "frontmatter": {
        "title": "看伴娘",
        "date": "2023-05-25T00:00:00.000Z",
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E6%8F%92%E4%BB%B6%E7%9C%8B%E6%9D%BF%E5%A8%98.html",
      "relativePath": "我的文章/vuepress/插件看板娘.md",
      "key": "v-6c2252cf",
      "path": "/%E6%88%91%E7%9A%84%E6%96%87%E7%AB%A0/vuepress/%E6%8F%92%E4%BB%B6%E7%9C%8B%E6%9D%BF%E5%A8%98.html",
      "headers": [
        {
          "level": 2,
          "title": "看板娘介绍",
          "slug": "看板娘介绍"
        },
        {
          "level": 2,
          "title": "看板娘安装",
          "slug": "看板娘安装"
        }
      ],
      "excerpt": "<h2 id=\"看板娘介绍\"><a class=\"header-anchor\" href=\"#看板娘介绍\">#</a> 看板娘介绍</h2>\n<blockquote>\n<p><a href=\"http://v1.vuepress-reco.recoluan.com/views/plugins/kanbanniang.html\" target=\"_blank\" rel=\"noopener noreferrer\">网址<OutboundLink/></a>\n<a href=\"https://github.com/QiShaoXuan/vuepress-plugin-cat\" target=\"_blank\" rel=\"noopener noreferrer\">github<OutboundLink/></a></p>\n</blockquote>\n<ul>\n<li>As plugin: @vuepress-reco/vuepress-plugin-kan-ban-niang</li>\n<li>As component: KanBanNiang（自动出现在页面中，无需添加额外代码）</li>\n</ul>\n"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "typora Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/typora/",
      "key": "v-89d5379c",
      "path": "/tag/typora/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vuepress Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "typora Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/typora/",
      "key": "v-6e983184",
      "path": "/categories/typora/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "vuepress Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/vuepress/",
      "key": "v-9fa33418",
      "path": "/categories/vuepress/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "logo": "/img/shan.png",
    "smoothScroll": true,
    "authorAvatar": "/img/avatar.png",
    "lastUpdated": "Last Updated",
    "author": "cc",
    "startYear": "2023",
    "nav": [
      {
        "text": "我的文章",
        "items": [
          {
            "text": "vuepress",
            "items": [
              {
                "text": "侧边栏",
                "link": "/我的文章/vuepress/侧边栏"
              },
              {
                "text": "插件看板娘",
                "link": "/我的文章/vuepress/插件看板娘"
              },
              {
                "text": "官方插件使用",
                "link": "/我的文章/vuepress/官方插件使用"
              },
              {
                "text": "图片显示",
                "link": "/我的文章/vuepress/图片显示"
              }
            ]
          },
          {
            "text": "typora",
            "items": [
              {
                "text": "安装pandoc",
                "link": "/我的文章/typora/安装pandoc"
              }
            ]
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2,
    "subSidebar": "auto",
    "search": true,
    "searchMaxSuggestions": 10,
    "record": "沪ICP备xxxxx号-6",
    "recordLink": "https://beian.miit.gov.cn/",
    "cyberSecurityRecord": "沪公网安备 xxxxxxx号",
    "cyberSecurityLink": "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=xxx05177",
    "friendLink": [
      {
        "title": "myblok",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "206214729@qq.com",
        "link": "_black"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}