/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "typora": {
      "key": "typora",
      "scope": "tags",
      "path": "/tag/typora/",
      "pageKeys": [
        "v-6d20d3b0"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-5164cbda",
        "v-5f9bdcaa",
        "v-295f4e8d",
        "v-6c2252cf"
      ]
    }
  },
  "categories": {
    "typora": {
      "key": "typora",
      "scope": "categories",
      "path": "/categories/typora/",
      "pageKeys": [
        "v-6d20d3b0"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "categories",
      "path": "/categories/vuepress/",
      "pageKeys": [
        "v-5164cbda",
        "v-5f9bdcaa",
        "v-295f4e8d",
        "v-6c2252cf"
      ]
    }
  },
  "timeline": {}
}